// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xz.Node.Repository;

namespace Xz.Node.Repository.Migrations
{
    [DbContext(typeof(XzDbContext))]
    [Migration("20210810133953_AddConfigTabdle")]
    partial class AddConfigTabdle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Xz.Node.Framework.Model.SysTable", b =>
                {
                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TableDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SysTables");
                });

            modelBuilder.Entity("Xz.Node.Framework.Model.SysTableColumn", b =>
                {
                    b.Property<string>("ColumnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsDisplay")
                        .HasColumnType("int");

                    b.Property<int?>("IsKey")
                        .HasColumnType("int");

                    b.Property<int?>("IsNull")
                        .HasColumnType("int");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.ToTable("SysTableColumns");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Auth.Auth_ModuleElementInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Attr")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("元素附加属性");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("元素样式");

                    b.Property<string>("DomId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("DOM ID");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("元素图标");

                    b.Property<string>("ModuleId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("功能模块Id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("名称");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<string>("Script")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("元素调用脚本");

                    b.Property<int>("Sort")
                        .HasColumnType("int")
                        .HasComment("排序字段");

                    b.Property<string>("TypeId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类ID");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类名称");

                    b.HasKey("Id");

                    b.ToTable("Auth_ModuleElement");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Auth.Auth_ModuleInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CascadeId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("节点语义ID");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("模块标识");

                    b.Property<string>("HotKey")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("热键");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("节点图标文件名称");

                    b.Property<bool>("IsAutoExpand")
                        .HasColumnType("bit")
                        .HasComment("是否自动展开");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("bit")
                        .HasComment("是否叶子节点");

                    b.Property<bool>("IsSys")
                        .HasColumnType("bit")
                        .HasComment("是否系统模块");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("名称");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("父节点流水号");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("父节点名称");

                    b.Property<int>("SortNo")
                        .HasColumnType("int")
                        .HasComment("排序号");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("当前状态");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("主页面URL");

                    b.Property<string>("Vector")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("矢量图标");

                    b.HasKey("Id");

                    b.ToTable("Auth_Module");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Auth.Auth_OrgInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BizCode")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("业务对照码");

                    b.Property<string>("CascadeId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("节点语义ID");

                    b.Property<int>("CreateId")
                        .HasColumnType("int")
                        .HasComment("创建人ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("CustomCode")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("自定义扩展码");

                    b.Property<string>("HotKey")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("热键");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("节点图标文件名称");

                    b.Property<bool>("IsAutoExpand")
                        .HasColumnType("bit")
                        .HasComment("是否自动展开");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("bit")
                        .HasComment("是否叶子节点");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("名称");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("父节点流水号");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("父节点名称");

                    b.Property<int>("SortNo")
                        .HasColumnType("int")
                        .HasComment("排序号");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("当前状态");

                    b.Property<string>("TypeId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类ID");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类名称");

                    b.HasKey("Id");

                    b.ToTable("Auth_Org");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Auth.Auth_RelevanceInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("描述");

                    b.Property<string>("ExtendInfo")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("扩展信息");

                    b.Property<string>("FirstId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("第一个表主键ID");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("映射标识");

                    b.Property<DateTime>("OperateTime")
                        .HasColumnType("datetime2")
                        .HasComment("授权时间");

                    b.Property<string>("OperatorId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("授权人");

                    b.Property<string>("SecondId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("第二个表主键ID");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("状态");

                    b.Property<string>("ThirdId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("第三个主键");

                    b.HasKey("Id");

                    b.ToTable("Auth_Relevance");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Auth.Auth_ResourceInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("资源所属应用ID");

                    b.Property<string>("AppName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("所属应用名称");

                    b.Property<string>("CascadeId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("节点语义ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建人ID");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建人");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("描述");

                    b.Property<bool>("Disable")
                        .HasColumnType("bit")
                        .HasComment("是否可用");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("名称");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("父节点流水号");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("父节点名称");

                    b.Property<int>("SortNo")
                        .HasColumnType("int")
                        .HasComment("排序号");

                    b.Property<string>("TypeId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类ID");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类名称");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间");

                    b.Property<string>("UpdateUserId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("最后更新人ID");

                    b.Property<string>("UpdateUserName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("最后更新人");

                    b.HasKey("Id");

                    b.ToTable("Auth_Resource");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Auth.Auth_RoleInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建人ID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("角色名称");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("当前状态");

                    b.Property<string>("TypeId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类ID");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类名称");

                    b.HasKey("Id");

                    b.ToTable("Auth_Role");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Auth.Auth_UserInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("用户登录帐号");

                    b.Property<string>("BizCode")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("业务对照码");

                    b.Property<string>("CreateId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建人");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("经办时间");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("用户姓名");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("密码");

                    b.Property<int>("Sex")
                        .HasColumnType("int")
                        .HasComment("性别");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("用户状态");

                    b.Property<string>("TypeId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类ID");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类名称");

                    b.HasKey("Id");

                    b.ToTable("Auth_User");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.System.System_ApplicationInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppSecret")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用密钥");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建日期");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建人");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用描述");

                    b.Property<bool>("Disable")
                        .HasColumnType("bit")
                        .HasComment("是否可用");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用图标");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用名称");

                    b.HasKey("Id");

                    b.ToTable("System_Application");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.System.System_ConfigurationInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id");

                    b.Property<string>("Category")
                        .HasColumnName("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnName("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("创建用户Id");

                    b.Property<string>("Creater")
                        .HasColumnName("Creater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建用户");

                    b.Property<int>("DisplayNo")
                        .HasColumnName("DisplayNo")
                        .HasColumnType("int")
                        .HasComment("顺序号");

                    b.Property<bool>("IsDelete")
                        .HasColumnName("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("是否物理删除");

                    b.Property<bool>("IsHide")
                        .HasColumnName("IsHide")
                        .HasColumnType("bit")
                        .HasComment("是否隐藏");

                    b.Property<string>("Remark")
                        .HasColumnName("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<string>("Text")
                        .HasColumnName("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("值显示值");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnName("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnName("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("更新用户Id");

                    b.Property<string>("Updater")
                        .HasColumnName("Updater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("更新用户");

                    b.Property<string>("Value")
                        .HasColumnName("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("值");

                    b.HasKey("Id");

                    b.ToTable("System_Configuration");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.System.System_DataPrivilegeRuleInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnName("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("创建用户Id");

                    b.Property<string>("Creater")
                        .HasColumnName("Creater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建用户");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("权限描述");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit")
                        .HasComment("是否可用");

                    b.Property<bool>("IsDelete")
                        .HasColumnName("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("是否物理删除");

                    b.Property<string>("PrivilegeRules")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("权限规则");

                    b.Property<int>("SortNo")
                        .HasColumnType("int")
                        .HasComment("排序号");

                    b.Property<string>("SourceCode")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("模块编号");

                    b.Property<string>("SubSourceCode")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("二级资源标识");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnName("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnName("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("更新用户Id");

                    b.Property<string>("Updater")
                        .HasColumnName("Updater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("更新用户");

                    b.HasKey("Id");

                    b.ToTable("System_DataPrivilegeRule");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.System.System_OpenJobInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建人ID");

                    b.Property<string>("CreateUserName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建人");

                    b.Property<string>("Cron")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("CRON表达式");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int")
                        .HasComment("异常次数");

                    b.Property<string>("JobCall")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("任务地址");

                    b.Property<string>("JobCallParams")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("任务参数，JSON格式");

                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("任务名称");

                    b.Property<int>("JobType")
                        .HasColumnType("int")
                        .HasComment("任务执行方式0：本地任务；1：外部接口任务");

                    b.Property<DateTime?>("LastErrorTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后一次失败时间");

                    b.Property<DateTime?>("LastRunTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后一次执行时间");

                    b.Property<DateTime?>("NextRunTime")
                        .HasColumnType("datetime2")
                        .HasComment("下次执行时间");

                    b.Property<string>("OrgId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("所属部门");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("RunCount")
                        .HasColumnType("int")
                        .HasComment("任务执行次数");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("任务运行状态（0：停止，1：正在运行，2：暂停）");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("最后更新时间");

                    b.Property<string>("UpdateUserId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("最后更新人ID");

                    b.Property<string>("UpdateUserName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("最后更新人");

                    b.HasKey("Id");

                    b.ToTable("System_OpenJob");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.System.System_SysLogInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Application")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("日志内容");

                    b.Property<string>("CreateId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("操作人ID");

                    b.Property<string>("CreateName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("操作人");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("记录时间");

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("操作所属模块地址");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("操作机器的IP地址");

                    b.Property<int>("Result")
                        .HasColumnType("int")
                        .HasComment("操作的结果：0：成功；1：失败；");

                    b.Property<string>("TypeId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类ID");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("分类名称");

                    b.HasKey("Id");

                    b.ToTable("System_SysLog");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Test.Test_CodeInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id");

                    b.Property<string>("Column1")
                        .HasColumnName("Column1")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("字段1");

                    b.Property<string>("Column2")
                        .HasColumnName("Column2")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("字段2");

                    b.Property<string>("Column3")
                        .HasColumnName("Column3")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("字段3");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnName("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("创建用户Id");

                    b.Property<string>("Creater")
                        .HasColumnName("Creater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建用户");

                    b.Property<bool>("IsDelete")
                        .HasColumnName("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("是否物理删除");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnName("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnName("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("更新用户Id");

                    b.Property<string>("Updater")
                        .HasColumnName("Updater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("更新用户");

                    b.HasKey("Id");

                    b.ToTable("Test_Code");

                    b.HasComment("测试类");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Test.Test_OaInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnName("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("创建用户Id");

                    b.Property<string>("Creater")
                        .HasColumnName("Creater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建用户");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用描述");

                    b.Property<bool>("Disable")
                        .HasColumnName("Disable")
                        .HasColumnType("bit")
                        .HasComment("是否可用");

                    b.Property<bool>("IsDelete")
                        .HasColumnName("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("是否物理删除");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用名称");

                    b.Property<Guid>("TestOpForeignKey")
                        .HasColumnName("TestOpForeignKey")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("TestOpForeignKey");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnName("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnName("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("更新用户Id");

                    b.Property<string>("Updater")
                        .HasColumnName("Updater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("更新用户");

                    b.HasKey("Id");

                    b.HasIndex("TestOpForeignKey")
                        .IsUnique();

                    b.ToTable("Test_Oa");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Test.Test_ObInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnName("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("创建用户Id");

                    b.Property<string>("Creater")
                        .HasColumnName("Creater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建用户");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用描述");

                    b.Property<bool>("Disable")
                        .HasColumnName("Disable")
                        .HasColumnType("bit")
                        .HasComment("是否可用");

                    b.Property<bool>("IsDelete")
                        .HasColumnName("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("是否物理删除");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用名称");

                    b.Property<Guid>("TestOpForeignKey")
                        .HasColumnName("TestOpForeignKey")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("TestOpForeignKey");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnName("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnName("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("更新用户Id");

                    b.Property<string>("Updater")
                        .HasColumnName("Updater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("更新用户");

                    b.HasKey("Id");

                    b.HasIndex("TestOpForeignKey");

                    b.ToTable("Test_Ob");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Test.Test_OcInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnName("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("创建用户Id");

                    b.Property<string>("Creater")
                        .HasColumnName("Creater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建用户");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用描述");

                    b.Property<bool>("Disable")
                        .HasColumnName("Disable")
                        .HasColumnType("bit")
                        .HasComment("是否可用");

                    b.Property<bool>("IsDelete")
                        .HasColumnName("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("是否物理删除");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用名称");

                    b.Property<Guid>("TestOpForeignKey")
                        .HasColumnName("TestOpForeignKey")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("TestOpForeignKey");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnName("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnName("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("更新用户Id");

                    b.Property<string>("Updater")
                        .HasColumnName("Updater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("更新用户");

                    b.HasKey("Id");

                    b.HasIndex("TestOpForeignKey")
                        .IsUnique();

                    b.ToTable("Test_Oc");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Test.Test_OmInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnName("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("创建用户Id");

                    b.Property<string>("Creater")
                        .HasColumnName("Creater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建用户");

                    b.Property<bool>("IsDelete")
                        .HasColumnName("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("是否物理删除");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用名称");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnName("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnName("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("更新用户Id");

                    b.Property<string>("Updater")
                        .HasColumnName("Updater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("更新用户");

                    b.HasKey("Id");

                    b.ToTable("Test_Om");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Test.Test_OnInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnName("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("创建用户Id");

                    b.Property<string>("Creater")
                        .HasColumnName("Creater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建用户");

                    b.Property<bool>("IsDelete")
                        .HasColumnName("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("是否物理删除");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用名称");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnName("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnName("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("更新用户Id");

                    b.Property<string>("Updater")
                        .HasColumnName("Updater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("更新用户");

                    b.HasKey("Id");

                    b.ToTable("Test_On");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Test.Test_On_OmInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnName("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("创建用户Id");

                    b.Property<string>("Creater")
                        .HasColumnName("Creater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建用户");

                    b.Property<bool>("IsDelete")
                        .HasColumnName("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("是否物理删除");

                    b.Property<Guid>("TestOmKey")
                        .HasColumnName("TestOmKey")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("TestOm主键");

                    b.Property<Guid>("TestOnKey")
                        .HasColumnName("TestOnKey")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("TestOn主键");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnName("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnName("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("更新用户Id");

                    b.Property<string>("Updater")
                        .HasColumnName("Updater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("更新用户");

                    b.HasKey("Id");

                    b.HasIndex("TestOmKey");

                    b.HasIndex("TestOnKey");

                    b.ToTable("Test_On_Om");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Test.Test_OpInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id");

                    b.Property<string>("AppSecret")
                        .HasColumnName("AppSecret")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用密钥");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnName("CreateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("创建用户Id");

                    b.Property<string>("Creater")
                        .HasColumnName("Creater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("创建用户");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用描述");

                    b.Property<bool>("Disable")
                        .HasColumnName("Disable")
                        .HasColumnType("bit")
                        .HasComment("是否可用");

                    b.Property<string>("Icon")
                        .HasColumnName("Icon")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用图标");

                    b.Property<bool>("IsDelete")
                        .HasColumnName("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("是否物理删除");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("应用名称");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnName("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnName("UpdateUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("更新用户Id");

                    b.Property<string>("Updater")
                        .HasColumnName("Updater")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("更新用户");

                    b.HasKey("Id");

                    b.ToTable("Test_Op");
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Test.Test_OaInfo", b =>
                {
                    b.HasOne("Xz.Node.Repository.Domain.Test.Test_OpInfo", "TestOp")
                        .WithOne("TestOa")
                        .HasForeignKey("Xz.Node.Repository.Domain.Test.Test_OaInfo", "TestOpForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Test.Test_ObInfo", b =>
                {
                    b.HasOne("Xz.Node.Repository.Domain.Test.Test_OpInfo", "TestOp")
                        .WithMany("Test_Obs")
                        .HasForeignKey("TestOpForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Test.Test_OcInfo", b =>
                {
                    b.HasOne("Xz.Node.Repository.Domain.Test.Test_OpInfo", "TestOp")
                        .WithOne("TestOc")
                        .HasForeignKey("Xz.Node.Repository.Domain.Test.Test_OcInfo", "TestOpForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Xz.Node.Repository.Domain.Test.Test_On_OmInfo", b =>
                {
                    b.HasOne("Xz.Node.Repository.Domain.Test.Test_OmInfo", "TestOm")
                        .WithMany("Test_On_Oms")
                        .HasForeignKey("TestOmKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Xz.Node.Repository.Domain.Test.Test_OnInfo", "TestOn")
                        .WithMany("Test_On_Oms")
                        .HasForeignKey("TestOnKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
